---
- name: Create root
  file:
    path: "{{ pki_folder }}/root"
    state: directory

- name: Create infra data folders for RabbitMq
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pki_folder }}/rabbitmq/ca"
    - "{{ pki_folder }}/rabbitmq/server"
    - "{{ pki_folder }}/rabbitmq/clients"
  when: rabbitmq_ssl

- name: Create infra data folders for HTTPS
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pki_folder }}/https/ca"
    - "{{ pki_folder }}/https/server"
    - "{{ pki_folder }}/https/clients/revoked"
  when: frontend_openssl

- name: Create infra data folders for PSQL
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pki_folder }}/psql/ca"
    - "{{ pki_folder }}/psql/server"
    - "{{ pki_folder }}/psql/clients/revoked"
  when: postgresql_ssl

- name: Create new infra data file
  template:
    src: infra.yml.j2
    dest: "{{ infra_data_file }}"
    force: no

- name: Generate root
  command: "bash '{{ pki_scripts_folder }}/gen_root.sh' -f '{{ pki_folder }}' -c '{{ config_root }}'"

- name: Generate HTTPS PKI
  command: 'bash "{{ pki_scripts_folder }}/gen_https_pki.sh" -f "{{ pki_folder }}" -c "{{ config_ca_https }}" -s "{{ config_server_https }}"'
  when: frontend_openssl

- name: Generate RabbitMq PKI
  command: 'bash "{{ pki_scripts_folder }}/gen_rabbitmq_pki.sh" -f "{{ pki_folder }}" -c "{{ config_ca_rabbitmq }}"'
  when: rabbitmq_ssl

- name: Generate PSQL PKI
  command: 'bash "{{ pki_scripts_folder }}/gen_psql_pki.sh" -d "{{ pki_folder }}" -c "{{ config_ca_psql }}" -s "{{ config_server_psql }}" -f "{{ config_frontend_psql }}"'
  when: postgresql_ssl
