---

- name: Install | Download tar.gz file from website
  get_url:
    url={{ pureftpd_tarball_url }}
    dest=/tmp/{{ pureftpd_tarball_name }}

- name: Install | Unpack PureFTPD
  shell: tar -xvjf {{ pureftpd_tarball_name }} chdir=/tmp

- name: Install | Compile and install PureFTPD
  shell: ./configure && make install-strip chdir=/tmp/{{ pureftpd_tag_name }}
  sudo: true
