stages:
  - pep8
  - unit_test
  - functional_test
  - build-ui

# This is NOT a job and will be ignored by GitLab-CI
.init_env_pep8_unittest: &init_env  # This is an anchor
  before_script:
    - cd $CI_PROJECT_DIR/$DIR
    - virtualenv --system-site-packages --python=python3 venv
    - venv/bin/pip install --quiet pep8 nosexcover pylint
    - venv/bin/pip install -r requirements.txt

frontend_pep8:
  <<: *init_env
  stage: pep8
  variables:
    DIR: frontend
  script:
    - venv/bin/pep8 config extras api tests --exclude=extras/migration

frontend_test:
  <<: *init_env
  stage: unit_test
  variables:
    DIR: frontend
  script:
    - venv/bin/nosetests --with-coverage --cover-xml --cover-package=api,config --with-xunit --cover-erase tests/

brain_pep8:
  <<: *init_env
  stage: pep8
  variables:
    DIR: brain
  script:
    - venv/bin/pep8 config extras brain tests --exclude=tests/old,extras/migration

brain_test:
  <<: *init_env
  stage: unit_test
  variables:
    DIR: brain
  script:
    - venv/bin/nosetests --with-coverage --cover-xml --cover-package=brain --with-xunit --cover-erase tests/

probe_pep8:
  <<: *init_env
  stage: pep8
  variables:
    DIR: probe
  script:
    - venv/bin/pep8 config probe tests --exclude=tests/old

probe_test:
  <<: *init_env
  stage: unit_test
  variables:
    DIR: probe
  script:
    - venv/bin/nosetests --with-coverage --cover-xml --cover-package=probe --with-xunit --cover-erase tests/

web-ui:
  stage: build-ui
  before_script:
    - cd $CI_PROJECT_DIR/frontend/web
  script:
    - npm install
    - ./node_modules/.bin/bower update
    - ./node_modules/.bin/gulp dist
    - cp -a dist $CI_PROJECT_DIR/
  artifacts:
    name: "core-webui-${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - dist/
  when: manual
