---

- name: Ensure good rights on IRMA-Probe install directory
  file:
    path: "{{ probe_project_dir }}"
    state: directory
    owner: "{{ probe_user }}"
    group: "{{ irma_server_group }}"
    mode: "u=rwX,g=rX,o="
    recurse: yes

# vim: sw=2
