---

- name: ClamAV | Install package
  apt: name={{ item }} state=latest
  with_items:
    - clamav
    - clamav-base
    - clamav-freshclam
    - clamav-daemon
    - clamav-unofficial-sigs
  register: clamav_install

- name: ClamAV | Update virus definition
  shell: freshclam --quiet
  sudo: true
  when: clamav_install | changed
  notify: ClamAV | restart daemon
