---

# For now, AV is install in Immutability mode

- name: Install dependencies for McAfee installation
  apt: pkg={{ item }} state=present
  with_items:
    - unzip
    - curl

- name: McAfee VSCL | Check version
  command: /usr/local/uvscan/uvscan --version
  ignore_errors: yes
  register: mcafee

- include: install.yml
  when: mcafee | failed
