---

- set_fact:
    frontend_deployment_dir: "{{ frontend_project_dir }}/releases/{{ irma_deployment_release_name }}"

- name: Ensure that deployment directory has been created
  file:
    path: "{{ frontend_deployment_dir }}"
    state: directory

- name: Check if frontend src archive is present
  local_action: stat path="{{ playbook_dir }}/files/{{ irma_frontend_archive }}"
  when: irma_deployment_code_version != 'local'

- name: Check if common src archive is already present
  local_action: stat path="{{ playbook_dir }}/files/{{ irma_common_archive }}"
  when: irma_deployment_code_version != 'local'

- name: Deploy frontend src archive
  unarchive:
    src: "files/{{ irma_frontend_archive }}"
    dest: "{{ frontend_deployment_dir }}"
  when: irma_deployment_code_version != 'local'

- name: Remove common symlink
  file:
    path: "{{ frontend_deployment_dir }}/lib"
    state: absent
  when: irma_deployment_code_version != 'local'

- name: Create lib directory
  file:
    path: "{{ frontend_deployment_dir }}/lib"
    state: directory
  when: irma_deployment_code_version != 'local'

- name: Deploy frontend-common src archive
  unarchive:
    src: "files/{{ irma_common_archive }}"
    dest: "{{ frontend_deployment_dir }}/lib"
  when: irma_deployment_code_version != 'local'

- name: Install requirements in a Frontend virtualenv
  pip:
    requirements: "{{ frontend_deployment_dir }}/requirements.txt"
    virtualenv: "{{ frontend_deployment_dir }}/venv"
    virtualenv_site_packages: yes
    extra_args: "{{ pip_extra_args | default('') }}"

- name: Configure config/frontend.ini file
  ini_file:
    dest: "{{ frontend_deployment_dir }}/config/frontend.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ frontend_deployment_configs }}"

- name: Create symlink release -> current
  file:
    src: "{{ frontend_deployment_dir }}"
    dest: "{{ frontend_install_dir }}"
    state: link

- name: Restart Supervisor services
  supervisorctl:
    name: "{{ item.name }}"
    state: restarted
  become: yes
  with_items: "{{ supervisor_programs_frontend }}"

- name: Initialize Database
  shell : "{{ frontend_deployment_dir }}/venv/bin/alembic upgrade head"
  args:
    chdir: "{{ frontend_deployment_dir }}"

- include: webui_build.yml
  when: irma_environment != 'production'

- include: webui_dist.yml
  when: irma_environment == 'production'
