---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend.irma
    ip: 172.16.1.30
    hostname: frontend.irma
    memory: 2048
  - name: brain.irma
    ip: 172.16.1.31
    hostname: brain.irma
    memory: 2048
  - name: probe.irma
    ip: 172.16.1.32
    hostname: probe.irma
    memory: 2048
