---
# Variables used by Vagrantfile are defined here

servers:
  - name: frontend.irma
    ip: 172.16.1.30
    hostname: frontend.irma
    memory: 2048
  - name: brain.irma
    ip: 172.16.1.31
    hostname: brain.irma
    memory: 2048
  - name: clamav.irma
    ip: 172.16.1.32
    hostname: clamav.irma
    memory: 2048
  - name: comodo.irma
    ip: 172.16.1.33
    hostname: comodo.irma
    memory: 2048

