---
# Variables used by Vagrantfile are defined here

servers:
  - name: brain.irma
    box: quarkslab/debian-9.0.0-amd64
    ip: 172.16.1.30
    hostname: brain.irma
    cpus: 2
    cpuexecutioncap: 100
    memory: 2048
    shares:
      - share_from: ../common
        share_to: /opt/irma/irma-common/releases/sync
        share_exclude:
          - .git/
          - venv/
      - share_from: ../frontend
        share_to: /opt/irma/irma-frontend/releases/sync
        share_exclude:
          - .git/
          - venv/
          - web/dist
          - web/node_modules
          - app/components
      - share_from: ../brain
        share_to: /opt/irma/irma-brain/releases/sync
        share_exclude:
          - .git/
          - venv/
          - db/
      - share_from: ../probe
        share_to: /opt/irma/irma-probe/releases/sync
        share_exclude:
          - .git/
          - venv/

libvirt_config:
  driver: kvm
  # connect_via_ssh: true
  # host:
  # username:
  # storage_pool_name:
  # id_ssh_key_file:

ansible_config:
  extra_vars:
    vagrant: true
    irma_environment: development
  groups:
    frontend: brain.irma
    sql-server: brain.irma
    brain: brain.irma
    comodo: brain.irma
    lief: brain.irma
    trid: brain.irma
    "probe:children":
      - comodo
      - lief
      - trid
