---

- name: Chocolatey | Check if already installed
  raw: choco.exe
  register: result
  failed_when: result.rc != 0 and result.rc != 1

- name: Chocolatey | Install
  script: chocolatey.bat
  when: result.stdout == ""
