---

- name: Determine remote_tmp variable
  raw: CMD /C echo '%TEMP%'
  register: echo_temp

- set_fact:
    remote_tmp: '{{ echo_temp.stdout_lines[0] | regex_replace("\\\\", "/") }}'

- name: Determine ProgramFiles(x86)
  raw: CMD /C echo '%PROGRAMFILES(x86)%'
  register: echo_programfiles

- set_fact:
    remote_programfile: '{{ echo_programfiles.stdout_lines[0] | regex_replace("\\\\", "/") }}'

## Install
- name: Checking if install path exists
  win_stat:
    path: '{{ remote_programfile }}/{{ emsisoft_win_install_path }}/'
  register: emsisoft_win_path_exists

- name: Create install path
  raw: "powershell -command \"md -Force '{{ remote_programfile }}/{{ emsisoft_win_install_path }}';\""
  when: not emsisoft_win_path_exists.stat.exists

- name: Checking if already installed
  win_stat:
    path: '{{ remote_programfile }}/{{ emsisoft_win_install_path }}/a2cmd.exe'
  register: emsisoft_win_installed

- name: Download installation archive
  raw: "powershell -command \"(new-object net.webclient).DownloadFile('{{ emsisoft_win_url }}', '{{ remote_tmp }}/a2cmd.zip');\""
  when: not emsisoft_win_installed.stat.exists

- name: Extract Emsisoft a2cmd
  raw: "powershell -command \"Add-Type -assembly 'system.io.compression.filesystem'; [io.compression.zipfile]::ExtractToDirectory('{{ remote_tmp }}/a2cmd.zip', '{{ remote_programfile }}/{{ emsisoft_win_install_path }}/')\""
  when: not emsisoft_win_installed.stat.exists

## Update
- name: Install a2cmd signatures
  raw: >
    powershell -command "cd '{{ remote_programfile }}/{{ emsisoft_win_install_path }}';"
                        "cmd /c a2cmd.exe /u;"
