---

- name: Determine remote_tmp variable
  raw: CMD /C echo '%TEMP%'
  register: echo_temp

- set_fact:
    remote_tmp: '{{ echo_temp.stdout_lines[0] | regex_replace("\\\\", "/") }}'

- name: Determine ProgramFiles(x86)
  raw: CMD /C echo '%PROGRAMFILES(x86)%'
  register: echo_programfiles

- set_fact:
    remote_programfile: '{{ echo_programfiles.stdout_lines[0] | regex_replace("\\\\", "/") }}'

## Install
- name: Checking if install path exists
  win_stat:
    path: '{{ remote_programfile }}/{{ emsisoft_win_install_path }}'
  register: emsisoft_win_path_exists

- name: Create install path
  win_file:
    path: "{{ remote_programfile }}/{{ emsisoft_win_install_path }}"
    state: directory
  when: not emsisoft_win_path_exists.stat.exists

- name: Checking if already installed
  win_stat:
    path: '{{ remote_programfile }}/{{ emsisoft_win_install_path }}/a2cmd.exe'
  register: emsisoft_win_installed

- name: Download installation archive
  win_get_url:
    url: "{{ emsisoft_win_url }}"
    dest: "{{ remote_tmp }}/a2cmd.exe"
  when: not emsisoft_win_installed.stat.exists

- name: Uncompress Emsisoft archive
  win_command: "{{ remote_tmp }}/a2cmd.exe -s2 -d."
  args:
    chdir: "{{ remote_programfile }}/{{ emsisoft_win_install_path }}"
  when: not emsisoft_win_installed.stat.exists

## Update
- name: Install a2cmd signatures
  win_command: "\"{{ remote_programfile }}/{{ emsisoft_win_install_path }}/a2cmd.exe\" /u"
