---

# As the repositories are not cloned yet, we cannot get requirements.txt
- name: "Installing dependencies with pip system-wide"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - pefile
    - python-magic
