---

- include: debian_install_packages.yml
  when: ansible_distribution == 'Debian'

- include: hosts.yml


- name: Create IRMA directories
  file:
    path: "{{ item }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
    state: directory
  sudo: yes
  with_items:
    - /var/log/irma
    - /var/irma

- name: add a fancy message to the box
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 755
  when: build_environment|default("default") == "demo"
