---

- name: Install common needed packages for IRMA
  apt: name={{ item }} state=present
  with_items:
    - vim
    - aria2
    - git
    - python-pip
    - python-virtualenv

- name: Build /etc/hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}'
    state=present
  when: hostvars[item].ansible_default_ipv4.address is defined and vagrant|default(False) == False
  with_items: groups['all']

# For Vagrant, public address is on eth1 interface.
- name: Build /etc/hosts file (Vagrant)
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line='{{ hostvars[item].ansible_eth1.ipv4.address }} {{ item }}'
    state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined and vagrant|default(False) == True
  with_items: groups['all']
