---

# configure debian mirrors
- include: apt_mirrors.yml
  tags: apt
  when: ansible_distribution == 'Debian'

- name: Install common needed packages for IRMA
  apt: name={{ item }} state=present
  with_items:
    - vim
    - aria2
    - git
    - python-pip
    - python-virtualenv
  when: ansible_os_family == "Debian"

- name: Build /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}'
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined and vagrant|default(False) == False
  with_items: groups['all']

# For Vagrant, public address is on eth1 interface.
- name: Build /etc/hosts file (Vagrant)
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_eth1.ipv4.address }} {{ item }}'
    state: present
  when: hostvars[item].ansible_eth1.ipv4.address is defined and vagrant|default(False) == True
  with_items: groups['all']

- name: Create IRMA directories
  file:
    path: "{{ item }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
    state: directory
  sudo: yes
  with_items:
    - /var/log/irma
    - /var/irma

- name: add a fancy message to the box
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 755
  when: build_environment|default("default") == "demo"
