---

- name: F-Secure | Download Package
  get_url:
    url: "{{ fsecure_url }}"
    dest: "{{ fsecure_temp_dir }}/fsls.tar.gz"

- name: F-Secure | Extract installer
  command: tar xzf "{{ fsecure_temp_dir }}/fsls.tar.gz"
  args:
    chdir: "{{ fsecure_temp_dir }}/"

- name: F-Secure | Run installer in trial mode
  shell: echo | sh "{{ fsecure_temp_dir }}/fsls-{{ fsecure_version }}/fsls-{{ fsecure_version }}" --auto standalone lang=en noremotewui nolocallogin
  sudo: true
  when: fsecure_license_key is not defined

- name: F-Secure | Run installer in licensed mode
  shell: echo | sh "{{ fsecure_temp_dir }}/fsls-{{ fsecure_version }}/fsls-{{ fsecure_version }}" --auto psb fspsbs={{ fsecure_psb_server }} lang=en keycode={{ fsecure_license_key }} noremotewui nolocallogin
  sudo: true
  when: fsecure_license_key is defined

- name: F-Secure | Disable Web Interface and Firewall with fschooser
  shell: printf "f\nw\n\n" | /opt/f-secure/fsav/sbin/fschooser
  sudo: true
