---

# For now, AV is install in Immutability mode

- name: Install dependencies for McAfee installation
  apt: pkg={{ item }} state=present
  with_items:
    - unzip
    - curl

- name: McAfee VSCL | Check version
  command: /usr/local/uvscan/uvscan --version
  ignore_errors: yes
  register: mcafee

- include: install.yml
  when: mcafee | failed

- name: McAfee VSCL | Download Update
  command: wget -Nc -r -nd -l1 -A "avvepo????dat.zip" http://download.nai.com/products/DatFiles/4.x/nai/
  args:
    chdir: /tmp/

- shell: "ls /tmp/avvepo*"
  register: update_pkg

- shell: "unzip -o {{ item }} -d /tmp/ && rm -r {{ item }}"
  with_items: update_pkg.stdout_lines

- shell: "ls /tmp/avvdat-*"
  register: update

- shell: "unzip -o {{ item }} -d /usr/local/uvscan/ && rm {{ item }}"
  with_items: update.stdout_lines
