---
# file: tasks/main.yml

- name: Ensure that directory /var/www has www-data rights
  file:
    path=/var/www
    state=directory
    owner=www-data
    group=www-data

- name: Install needed packages (using apt; pip)
  apt: name={{ item }} state=latest
  with_items:
    - git

- pip: name={{ item }} state=present
  with_items:
    - virtualenv

- name: API | Install uWSGI config file
  template:
    src=frontend-api.ini.j2
    dest=/etc/uwsgi/vassals/{{ frontend_uwsgi_api_appname }}.ini
    owner=root
    group=root
    mode=0755

- name: Tasks | Install Celery app for Supervisor
  template:
    src=supervisor-celery.conf.j2
    dest=/etc/supervisor/conf.d/celery.conf
    owner=root
    group=root
    mode=0755
