---

- name: ComodoCAVL | Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - binutils
    - libqt4-sql
    - libqt4-network
    - libqtgui4

- name: ComodoCAVL | Download Package
  get_url:
    url: "{{ comodo_cavl_deb_url }}"
    dest: /tmp/comodo.deb
  when: ansible_os_family == "Debian"

- name: ComodoCAVL | Extract files
  shell: ar x /tmp/comodo.deb
  args:
    chdir: /tmp/
    creates: /tmp/data.tar.gz

- name: ComodoCAVL | Install files
  shell: tar xzf /tmp/data.tar.gz -C /

- shell: rm control.tar.gz data.tar.gz debian-binary
  args:
    chdir: /tmp/
