---

# NPM is extract to a package directory
- name: Copy and untar npm
  unarchive:
    src: npm/{{ nodejs_npm_filename }}
    dest: /tmp

- name: Install NPM
  shell: ./configure && make && make install
  become: yes
  args:
    chdir: /tmp/package
