---

- src: https://github.com/quarkslab/postgresql.git
  version: a45227559e9c7c1b1e952b53855ec1d631daaad2
  name: ANXS.postgresql

- src: https://github.com/weareinteractive/ansible-sudo.git
  version: 1.6.1
  name: franklinkim.sudo

- src: https://github.com/weareinteractive/ansible-ufw.git
  version: 1.6.0
  name: franklinkim.ufw

- src: https://github.com/jdauphant/ansible-role-nginx.git
  version: v2.7.4
  name: jdauphant.nginx

- src: https://github.com/quarkslab/ansible-playbook-rabbitmq.git
  version: 7684af260c06beb010958c9b6ae802690ab26f61
  name: Mayeu.RabbitMQ

- src: https://github.com/mivok/ansible-users.git
  version: v1.2.4
  name: mivok0.users

- src: https://github.com/willshersystems/ansible-sshd.git
  version: v0.4.7
  name: willshersystems.sshd
