---

- name: Ensure that directory /var/www has www-data rights
  file:
    path: /var/www
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_group }}"
    recurse: yes
  notify: restart nginx

- include: openssl_configuration.yml
  when: frontend_openssl|default(False) == True
